# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# https://github.com/marketplace/actions/github-action-for-flyctl
name: Release

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
